language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
script:
  - mkdir -p build/logs
  - phpunit --configuration tests/phpunit.xml
install: composer update
after_success:
  - ls -l build/logs
  - travis_retry php vendor/bin/coveralls -v