language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
install: composer update
script:
  - mkdir -p build/logs
  - phpunit --configuration tests/phpunit.xml
after_success:
  - cat build/logs/clover.xml
  - travis_retry php vendor/bin/coveralls -v